# Generated by Django 6.0.7 on 2026-08-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="image",
            field=models.ImageField(
                upload_to="images/blog", verbose_name="Изображение"
            ),
        ),
    ]
