# Generated by Django 6.0.7 on 2026-08-09 15:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_record_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="record",
            options={
                "ordering": ["id"],
                "verbose_name": "Запись",
                "verbose_name_plural": "Записи",
            },
        ),
        migrations.AddField(
            model_name="record",
            name="count_views",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Количество просмотров"
            ),
        ),
        migrations.AddField(
            model_name="record",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Дата создания",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="record",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активна"),
        ),
        migrations.AlterField(
            model_name="record",
            name="image",
            field=models.ImageField(
                upload_to="images/blog/", verbose_name="Изображение"
            ),
        ),
    ]
