# Generated by Django 6.0.7 on 2026-08-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_product_category_alter_product_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                upload_to="images/product", verbose_name="Изображение"
            ),
        ),
    ]
