# Generated by Django 6.0.7 on 2026-08-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                upload_to="images/product/", verbose_name="Изображение"
            ),
        ),
    ]
