# Generated by Django 6.0.7 on 2026-09-02 06:09

from django.db import migrations

from django.db import migrations

# Миграция
def create_moderators_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    # ContentType для модели Product из приложения catalog
    try:
        product_ct = ContentType.objects.get(app_label='catalog', model='product')
    except ContentType.DoesNotExist:
        print('⚠️ ContentType для catalog.product не найден, пропускаем')
        return

    # Разрешения для модератора
    permission_codenames = [
        'view_product',
        'delete_product',
        'can_unpublish_product',
    ]

    permissions = Permission.objects.filter(
        content_type=product_ct,
        codename__in=permission_codenames,
    )

    # Проверяем, что нашли все ожидаемые разрешения
    found = set(permissions.values_list('codename', flat=True))
    missing = set(permission_codenames) - found
    if missing:
        print(f'⚠️ Не найдены разрешения: {missing}')

    # Создаём группу или используем существующую
    group, is_created = Group.objects.get_or_create(name='Модератор продуктов')

    # Устанавливаем разрешения (полная замена)
    group.permissions.set(permissions)

    action = 'Создана' if is_created else 'Обновлена'
    print(f'✅ Группа "Модератор продуктов" {action}, прав назначено: {permissions.count()}')

# Откат миграции
def remove_moderators_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    deleted, _ = Group.objects.filter(name='Модератор продуктов').delete()
    print(f'🗑️ Удалено групп: {deleted}')


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_alter_product_options_product_status"),
    ]

    operations = [
        migrations.RunPython(
            create_moderators_group,
            remove_moderators_group,
        ),
    ]
